### PR TITLE
fix: Re-remove auth_ec2 double json parsing

### PR DESCRIPTION
**Pull request by sijis**
The double parsing seemed to have been re-introduced from #61.

Related: #76 

This prevents the following error from being thrown:
```
Traceback (most recent call last):
...
    return self.auth('/v1/auth/aws-ec2/login', json=params, use_token=use_token).json()
AttributeError: 'dict' object has no attribute 'json'

```

It does appear that #61 was merged in before #76 but looking at git blame the latest changes only reflect from #61. Maybe there was a rebase gone wrong along the way.

### CODE REVIEW

**Comment by jeffwecan** [comment]
Noice, I ran across the same thing in https://github.com/ianunruh/hvac/pull/181 but honestly probably should have broken out this change as its semi-unrelated to the scope of that linked PR. Want to cherry-pick in the regression test I added in https://github.com/ianunruh/hvac/commit/82b1a9ea76ae19eaff264a0435edfb10cce8134c to this PR? If so, I can get it merged. Alternatively, if you want to look over https://github.com/ianunruh/hvac/pull/181 and sign off on those changes, we could merge that PR and close this fella out.

**Comment by jeffwecan** [comment]
I ended up working through most of the other PRs in the backlog and merging https://github.com/ianunruh/hvac/pull/181 (which includes your fix as well). I'm aiming to do a new release that will include that change over the next week or so. In the meantime, I'm going to close out this PR; feel free to reopen it if you need to though!
